import { DesignConfig } from './index';

export const classicTemplate: DesignConfig = {
  digital: {
    template: 'classic',
    mood: 'light',
    density: 'normal',
    typography: {
      h1: { font: 'Cormorant Garamond', size: 36, weight: 700, color: '#2C2C2C', transform: 'none', spacing: 0 },
      h2: { font: 'Cormorant Garamond', size: 24, weight: 600, color: '#6B4C1E', transform: 'none', spacing: 0.02 },
      h3: { font: 'Lato', size: 16, weight: 600, color: '#333333' },
      body: { font: 'Lato', size: 14, weight: 400, color: '#666666', style: 'normal' },
      price: { font: 'Lato', size: 16, weight: 700, color: '#333333', format: '€ {price}' },
      meta: { font: 'Lato', size: 11, color: '#999999' },
    },
    colors: {
      pageBackground: '#FAFAF5',
      headerBackground: '#F5F0E8',
      headerText: '#2C2C2C',
      sectionHeaderBg: '#F5F0E8',
      sectionLine: '#D4C4A8',
      sectionLineWidth: 1,
      sectionLineStyle: 'double',
      productBg: 'transparent',
      productHover: '#F5F0E8',
      productDivider: '#E8E0D0',
      priceLine: 'dotted',
      priceLineColor: '#D4C4A8',
      accentPrimary: '#6B4C1E',
      accentRecommend: '#8B6914',
      accentNew: '#2E7D4F',
      accentPremium: '#8B2252',
    },
    icons: { style: 'outlined', sectionIcons: {} },
    badges: { show: ['recommendation', 'vegetarian', 'vegan'], style: 'dot' },
    allergens: { position: 'footer', style: 'numbers' },
    products: {
      showImages: false, imageStyle: 'color', imageShape: 'rectangle', imageSize: 48, imagePosition: 'left',
      showShortDesc: true, showLongDesc: false, descMaxLines: 2,
      pricePosition: 'right', currency: '€', priceFormat: '€ {price}', showAllPrices: true, showFillQuantity: true,
      wineDetails: ['winery', 'vintage', 'region', 'country'], wineDetailPosition: 'below',
      drinkDetails: ['alcohol'],
    },
    navigation: { showToc: true, tocPosition: 'top', tocStyle: 'list', stickyNav: false, smoothScroll: true, highlightActive: false, showBackToTop: true, hideEmptySections: true },
    header: { logo: null, logoPosition: 'center', logoSize: 100, title: null, subtitle: null, backgroundImage: null, overlayOpacity: 0.5, height: 'normal' },
    footer: { show: true, text: 'Hotel Sonnblick · Saalbach', showAllergenNote: true, showPriceNote: true },
  },
  analog: {
    template: 'classic',
    hierarchy: [
      { level: 'KATEGORIE', newPage: true, showText: true, showHeader: true },
      { level: 'PRODUKT', newPage: false, showText: true, showHeader: false },
    ],
    content: { groups: ['all'], showTitlePage: true, showToc: true, showLegend: false, showQrPage: false, freePages: [], interPages: false },
    language: { primary: 'de', secondary: 'en', secondaryScope: 'all', descriptionLang: 'both' },
    page: { format: 'A4', orientation: 'portrait', margins: 'wide', customMargins: null, bleed: false, pageNumbers: true, pageNumberStart: 1, countTitlePage: false },
    titlePage: { logo: null, logoBgColor: '#6B4C1E', logoBgImage: null, logoPosition: 'center', logoSize: 160, quote: null, quoteEN: null, quoteAuthor: null, quoteFont: 'Cormorant Garamond', freeBlocks: [] },
    toc: { depth: 'category', lineStyle: 'dotted', bilingual: true, indented: false, position: 'afterTitle' },
    typography: {
      sectionTitle: { font: 'Cormorant Garamond', size: 32, color: '#2C2C2C' },
      subCategory: { font: 'Lato', size: 13, weight: 700, color: '#555555' },
      subGrouping: { font: 'Cormorant Garamond', size: 16, color: '#333333' },
      productName: { font: 'Lato', size: 12, weight: 700, color: '#000000' },
      winery: { font: 'Lato', size: 10, color: '#777777' },
      description: { font: 'Lato', size: 10, color: '#333333', align: 'justify', lineHeight: 1.4 },
      price: { font: 'Lato', size: 11, weight: 700, color: '#000000' },
    },
    colors: { pageBg: '#FFFFFF', textMain: '#333333', accent: '#6B4C1E', priceColor: '#000000', footerColor: '#999999' },
    productLayout: {
      nameLineShow: ['icons'],
      wineryShow: ['winery', 'region'],
      descDE: true, descEN: true, descLayout: 'stacked', descAlign: 'justify', descMaxChars: 0,
      priceFormat: '{fill}  {price} €', multiplePrices: 'stacked',
      spacing: 'normal', dividerLine: true,
    },
    images: { show: false, position: 'pageBottom', maxPerRow: 4, height: 100, style: 'color', typeFilter: ['BOTTLE'] },
    headerFooter: {
      header: { repeatSectionName: false, font: 'Cormorant Garamond', dividerLine: true },
      footer: { show: true, textLeft: 'Inklusivpreise in Euro', textCenter: '', textRight: '{pageNumber}', dividerLine: true },
    },
    pageBreaks: { newPagePerMainCategory: true, noOrphanProducts: true, minProductsAfterHeader: 2, keepImagesWithText: true },
  },
};
