import { DesignConfig } from './index';

export const elegantTemplate: DesignConfig = {
  digital: {
    template: 'elegant',
    mood: 'warm',
    density: 'normal',
    typography: {
      h1: { font: 'Playfair Display', size: 32, weight: 700, color: '#2C1810', transform: 'none', spacing: 0.02 },
      h2: { font: 'Playfair Display', size: 22, weight: 600, color: '#8B6914', transform: 'uppercase', spacing: 0.05 },
      h3: { font: 'Source Sans 3', size: 16, weight: 600, color: '#333333' },
      body: { font: 'Source Sans 3', size: 14, weight: 400, color: '#777777', style: 'italic' },
      price: { font: 'Source Sans 3', size: 16, weight: 700, color: '#6B4C1E', format: '€ {price}' },
      meta: { font: 'Source Sans 3', size: 11, color: '#AAAAAA' },
    },
    colors: {
      pageBackground: '#FFF8F0',
      headerBackground: '#8B6914',
      headerText: '#FFFFFF',
      sectionHeaderBg: 'transparent',
      sectionLine: '#D4A853',
      sectionLineWidth: 1,
      sectionLineStyle: 'solid',
      productBg: 'transparent',
      productHover: '#FFF5E6',
      productDivider: '#F0E6D4',
      priceLine: 'dotted',
      priceLineColor: '#D4C4A8',
      accentPrimary: '#8B6914',
      accentRecommend: '#D4A853',
      accentNew: '#4A7C59',
      accentPremium: '#7B2D3F',
    },
    icons: { style: 'outlined', sectionIcons: {} },
    badges: { show: ['recommendation', 'new', 'premium', 'vegetarian', 'bio'], style: 'pill' },
    allergens: { position: 'product', style: 'numbers' },
    products: {
      showImages: true, imageStyle: 'color', imageShape: 'rounded', imageSize: 64, imagePosition: 'left',
      showShortDesc: true, showLongDesc: false, descMaxLines: 2,
      pricePosition: 'right', currency: '€', priceFormat: '€ {price}', showAllPrices: true, showFillQuantity: true,
      wineDetails: ['winery', 'vintage', 'grape', 'region'], wineDetailPosition: 'below',
      drinkDetails: ['alcohol', 'ingredients'],
    },
    navigation: { showToc: true, tocPosition: 'sticky', tocStyle: 'pills', stickyNav: true, smoothScroll: true, highlightActive: true, showBackToTop: true, hideEmptySections: true },
    header: { logo: null, logoPosition: 'center', logoSize: 120, title: null, subtitle: null, backgroundImage: null, overlayOpacity: 0.6, height: 'normal' },
    footer: { show: true, text: 'Hotel Sonnblick · Saalbach', showAllergenNote: true, showPriceNote: true },
  },
  analog: {
    template: 'elegant',
    hierarchy: [
      { level: 'KATEGORIE', newPage: true, showText: true, showHeader: true },
      { level: 'HERKUNFTSLAND', newPage: false, showText: true, showHeader: true },
      { level: 'REBSORTE', newPage: false, showText: false, showHeader: true },
      { level: 'PRODUKT', newPage: false, showText: true, showHeader: false },
    ],
    content: { groups: ['all'], showTitlePage: true, showToc: true, showLegend: true, showQrPage: true, freePages: [], interPages: false },
    language: { primary: 'de', secondary: 'en', secondaryScope: 'all', descriptionLang: 'both' },
    page: { format: 'A4', orientation: 'portrait', margins: 'normal', customMargins: null, bleed: false, pageNumbers: true, pageNumberStart: 1, countTitlePage: false },
    titlePage: { logo: null, logoBgColor: '#555555', logoBgImage: null, logoPosition: 'upperThird', logoSize: 200, quote: null, quoteEN: null, quoteAuthor: null, quoteFont: 'Dancing Script', freeBlocks: [] },
    toc: { depth: 'categoryAndCountry', lineStyle: 'dotted', bilingual: true, indented: true, position: 'afterTitle' },
    typography: {
      sectionTitle: { font: 'Dancing Script', size: 36, color: '#333333' },
      subCategory: { font: 'Source Sans 3', size: 14, weight: 700, color: '#333333' },
      subGrouping: { font: 'Playfair Display', size: 18, color: '#333333' },
      productName: { font: 'Source Sans 3', size: 12, weight: 700, color: '#000000' },
      winery: { font: 'Source Sans 3', size: 10, color: '#777777' },
      description: { font: 'Source Sans 3', size: 10, color: '#333333', align: 'justify', lineHeight: 1.4 },
      price: { font: 'Source Sans 3', size: 11, weight: 700, color: '#000000' },
    },
    colors: { pageBg: '#FFFFFF', textMain: '#333333', accent: '#C8A850', priceColor: '#000000', footerColor: '#999999' },
    productLayout: {
      nameLineShow: ['grapeAbbrev', 'appellation', 'style', 'icons'],
      wineryShow: ['winery', 'city', 'region'],
      descDE: true, descEN: true, descLayout: 'stacked', descAlign: 'justify', descMaxChars: 0,
      priceFormat: '{fill}  {price} €', multiplePrices: 'stacked',
      spacing: 'normal', dividerLine: false,
    },
    images: { show: true, position: 'pageBottom', maxPerRow: 4, height: 120, style: 'color', typeFilter: ['BOTTLE', 'LABEL'] },
    headerFooter: {
      header: { repeatSectionName: true, font: 'Dancing Script', dividerLine: true },
      footer: { show: true, textLeft: 'Inklusivpreise in Euro All prices incl. Taxes', textCenter: '', textRight: '{pageNumber}', dividerLine: true },
    },
    pageBreaks: { newPagePerMainCategory: true, noOrphanProducts: true, minProductsAfterHeader: 2, keepImagesWithText: true },
  },
};
