ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "lineageId" TEXT;
ALTER TABLE "TaxonomyNode" ADD COLUMN IF NOT EXISTS "taxRate" DOUBLE PRECISION;
ALTER TABLE "TaxonomyNode" ADD COLUMN IF NOT EXISTS "taxLabel" TEXT;
